# Generated by Django 5.2.6 on 2025-12-05 22:47

import appointments.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='end',
            field=appointments.fields.EncryptedDateTimeField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_name',
            field=appointments.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start',
            field=appointments.fields.EncryptedDateTimeField(),
        ),
    ]
