# Generated by Django 5.2.6 on 2025-10-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birth_date', models.DateField()),
                ('last_visit', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(max_length=30)),
            ],
        ),
    ]
