# Generated by Django 5.2.6 on 2025-10-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_visit',
        ),
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='patient',
            name='etatdesante',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='patient',
            name='profession',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
