# Generated by Django 5.2.6 on 2025-12-05 22:02

import patients.fields
import patients.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(storage=patients.storage.EncryptedFileSystemStorage(), upload_to='patient_documents/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='etatdesante',
            field=patients.fields.EncryptedTextField(default='N/A'),
        ),
    ]
