# Generated by Django 5.2.6 on 2025-12-05 22:07

import patients.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_document_file_alter_patient_etatdesante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=patients.fields.EncryptedTextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=patients.fields.EncryptedTextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=patients.fields.EncryptedTextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='profession',
            field=patients.fields.EncryptedTextField(default='N/A'),
        ),
    ]
